version: '3.6'

services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.38
    restart: 'unless-stopped'
    networks:
      - web
    expose:
      - 9091
    volumes:
      - '${PWD}/authelia:/config'
    environment:
      TZ: "Europe/Madrid"
    healthcheck:
      ## In production the healthcheck section should be commented.
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.${HTTP_HOST}`)"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=lets-encrypt"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"

  traefik:
    image: traefik:v3.1.2
    container_name: traefik
    env_file: .env
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_lets-encrypt_ACME_EMAIL=${EMAIL}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - authelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./traefik_dynamic.yaml:/traefik_dynamic.yaml
      - ./acme.json:/acme.json
    networks:
      - web

networks:
  web:
    external: true
